"""Adicionando exclusão em cascata

Revision ID: 412900560243
Revises: 
Create Date: 2025-04-19 12:18:32.802444

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '412900560243'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('agendamento', schema=None) as batch_op:
        batch_op.drop_constraint('agendamento_paciente_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'paciente', ['paciente_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('agendamento', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('agendamento_paciente_id_fkey', 'paciente', ['paciente_id'], ['id'])

    # ### end Alembic commands ###
